<script setup lang="ts">
const videoSrc = '/hero-video.mp4'

const items = [
  // Row 1-2: Hero video + two stacked cinematic shots
  { type: 'video', src: videoSrc, tool: 'Kling AI', icon: 'https://www.google.com/s2/favicons?domain=klingai.com&sz=64', prompt: '"Cinematic drone shot, neon-lit cityscape at golden hour"', span: 'col-span-6 sm:col-span-6 lg:col-span-7 row-span-2' },
  { type: 'image', src: '/2747d765-d130-405e-b300-f70212a33284.jpg', tool: 'Midjourney', icon: 'https://www.google.com/s2/favicons?domain=midjourney.com&sz=64', prompt: '"Action scene, Hong Kong rain, cinematic B&W"', span: 'col-span-6 sm:col-span-6 lg:col-span-5' },
  { type: 'image', src: '/2d963ed9-9e2c-4f3e-9659-fe24e96e624e.png', tool: 'Flux', icon: 'https://www.google.com/s2/favicons?domain=blackforestlabs.ai&sz=64', prompt: '"Noir car scene, moody fog, blue neon reflections"', span: 'col-span-6 sm:col-span-6 lg:col-span-5' },

  // Row 3: Four varied tiles
  { type: 'image', src: '/img-portrait.png', tool: 'DALL-E 3', icon: 'https://www.google.com/s2/favicons?domain=openai.com&sz=64', prompt: '"Hyperrealistic portrait, warm cinematic lighting"', span: 'col-span-6 sm:col-span-4 lg:col-span-3' },
  { type: 'image', src: '/94d0afde-5eb9-40e0-b3be-546fba0f885a.png', tool: 'Midjourney', icon: 'https://www.google.com/s2/favicons?domain=midjourney.com&sz=64', prompt: '"Neon gas station, eerie green fog, cinematic"', span: 'col-span-6 sm:col-span-4 lg:col-span-3' },
  { type: 'image', src: '/f17ce022-5b9a-4caa-b408-17cb8f85522e.jpg', tool: 'Ideogram', icon: 'https://www.google.com/s2/favicons?domain=ideogram.ai&sz=64', prompt: '"Abstract ink explosion, cyan and orange smoke"', span: 'col-span-6 sm:col-span-4 lg:col-span-3' },
  { type: 'image', src: '/img-fashion.png', tool: 'Flux', icon: 'https://www.google.com/s2/favicons?domain=blackforestlabs.ai&sz=64', prompt: '"Fashion editorial, retro sportswear, golden hour"', span: 'col-span-6 sm:col-span-12 lg:col-span-3' },

]
</script>

<template>
  <section class="relative section-pad overflow-hidden">
    <!-- Background -->
    <div class="absolute inset-0" style="background: linear-gradient(to bottom, #110f20 0%, #0a0914 40%, #07070f 100%);"></div>
    <div class="absolute top-[30%] left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-gold-500/[0.02] rounded-full blur-[80px]"></div>

    <!-- Header -->
    <div class="container-main relative z-10">
      <div class="grid lg:grid-cols-2 gap-6 items-end section-header reveal">
        <div>
          <span class="inline-block text-gold-400 text-xs font-bold tracking-[0.2em] uppercase mb-5">Made with PromptEdit</span>
          <h2 class="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white leading-[1.08] tracking-tight">
            See what's <span class="font-serif italic font-bold text-gold-400">possible.</span>
          </h2>
        </div>
        <p class="text-gray-400 text-base lg:text-lg lg:text-right max-w-md lg:ml-auto leading-relaxed">
          Real content generated by real creators. Every image, video, and audio — made with AI tools on PromptEdit.
        </p>
      </div>
    </div>

    <!-- Bento Grid -->
    <div class="container-wide relative z-10 reveal-scale">
      <div class="grid grid-cols-12 auto-rows-[160px] sm:auto-rows-[200px] lg:auto-rows-[240px] gap-2 sm:gap-3 lg:gap-4">
        <div
          v-for="(item, i) in items" :key="i"
          :class="[item.span, 'group relative rounded-2xl lg:rounded-3xl overflow-hidden cursor-pointer border border-white/[0.06] hover:border-white/15 transition-all duration-500']"
        >
          <!-- Media -->
          <video v-if="item.type === 'video'" autoplay muted loop playsinline class="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-[1.04]">
            <source :src="item.src" type="video/mp4" />
          </video>
          <img v-else :src="item.src" alt="" class="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-[1.06]" loading="lazy" decoding="async" />

          <!-- Gradient overlay -->
          <div class="absolute inset-0 bg-gradient-to-t from-dark-950/90 via-dark-950/10 to-transparent"></div>

          <!-- Video badge -->
          <div v-if="item.type === 'video'" class="absolute top-4 left-4 flex items-center gap-2 px-3 py-1.5 rounded-full bg-black/40 backdrop-blur-xl border border-white/10">
            <span class="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse"></span>
            <span class="text-[11px] text-white/80 font-semibold tracking-wide">AI Video</span>
          </div>

          <!-- Bottom info -->
          <div class="absolute bottom-0 left-0 right-0 p-4 lg:p-5 flex items-end justify-between">
            <div>
              <p class="text-[11px] text-gray-400/70 italic mb-2 line-clamp-1 hidden sm:block group-hover:text-gray-300 transition-colors">{{ item.prompt }}</p>
              <div class="flex items-center gap-2">
                <img :src="item.icon" alt="" class="w-4 h-4 rounded-sm" loading="lazy" decoding="async" />
                <span class="text-white font-semibold text-xs sm:text-sm">{{ item.tool }}</span>
              </div>
            </div>
            <a href="https://promptedit.com" target="_blank" class="text-xs font-semibold text-gold-400 opacity-0 translate-y-2 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-300 flex items-center gap-1 shrink-0">
              Try it <span class="inline-block transition-transform group-hover:translate-x-0.5">&rarr;</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
